[project]
name = "franka-datacapture"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pylsl>=1.17.6",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "vidgear>=0.3.4",
]
